#ifndef ROBOT_TAG_GAME_WORLD_INCLUDED
#define ROBOT_TAG_GAME_WORLD_INCLUDED

#include "radio/radio.h"

#define ROBOT_0_RADIO_ADDRESS { 0xAB, 0xAB, 0xAB, 0xAB, 0xCD }
#define BASE_RADIO_ADDRESS { 0xAB, 0xAB, 0xAB, 0xAB, 0xAB }
#define RADIO_CHANNEL 102
#define RADIO_RATE RADIO_1MBPS

#endif // ROBOT_TAG_GAME_WORLD_INCLUDED
