#ifndef RTOS_ARDUINO_PINS_INCLUDED
#define RTOS_ARDUINO_PINS_INCLUDED

#include "../util.h"
#include <avr/io.h>

#define SET_PIN0 SET_BIT(PORTE, PE0)
#define SET_PIN1 SET_BIT(PORTE, PE1)
#define SET_PIN2 SET_BIT(PORTE, PE4)
#define SET_PIN3 SET_BIT(PORTE, PE5)
#define SET_PIN4 SET_BIT(PORTG, PG5)
#define SET_PIN5 SET_BIT(PORTE, PE3)
#define SET_PIN6 SET_BIT(PORTH, PH3)
#define SET_PIN7 SET_BIT(PORTH, PH4)
#define SET_PIN8 SET_BIT(PORTH, PH5)
#define SET_PIN9 SET_BIT(PORTH, PH6)
#define SET_PIN10 SET_BIT(PORTB, PB4)
#define SET_PIN11 SET_BIT(PORTB, PB5)
#define SET_PIN12 SET_BIT(PORTB, PB6)
#define SET_PIN13 SET_BIT(PORTB, PB7)

#define CLEAR_PIN0 CLEAR_BIT(PORTE, PE0)
#define CLEAR_PIN1 CLEAR_BIT(PORTE, PE1)
#define CLEAR_PIN2 CLEAR_BIT(PORTE, PE4)
#define CLEAR_PIN3 CLEAR_BIT(PORTE, PE5)
#define CLEAR_PIN4 CLEAR_BIT(PORTG, PG5)
#define CLEAR_PIN5 CLEAR_BIT(PORTE, PE3)
#define CLEAR_PIN6 CLEAR_BIT(PORTH, PH3)
#define CLEAR_PIN7 CLEAR_BIT(PORTH, PH4)
#define CLEAR_PIN8 CLEAR_BIT(PORTH, PH5)
#define CLEAR_PIN9 CLEAR_BIT(PORTH, PH6)
#define CLEAR_PIN10 CLEAR_BIT(PORTB, PB4)
#define CLEAR_PIN11 CLEAR_BIT(PORTB, PB5)
#define CLEAR_PIN12 CLEAR_BIT(PORTB, PB6)
#define CLEAR_PIN13 CLEAR_BIT(PORTB, PB7)

#define SET_PIN0_OUT SET_BIT(DDRE, DDE0)
#define SET_PIN1_OUT SET_BIT(DDRE, DDE1)
#define SET_PIN2_OUT SET_BIT(DDRE, DDE4)
#define SET_PIN3_OUT SET_BIT(DDRE, DDE5)
#define SET_PIN4_OUT SET_BIT(DDRG, DDG5)
#define SET_PIN5_OUT SET_BIT(DDRE, DDE3)
#define SET_PIN6_OUT SET_BIT(DDRH, DDH3)
#define SET_PIN7_OUT SET_BIT(DDRH, DDH4)
#define SET_PIN8_OUT SET_BIT(DDRH, DDH5)
#define SET_PIN9_OUT SET_BIT(DDRH, DDH6)
#define SET_PIN10_OUT SET_BIT(DDRB, DDB4)
#define SET_PIN11_OUT SET_BIT(DDRB, DDB5)
#define SET_PIN12_OUT SET_BIT(DDRB, DDB6)
#define SET_PIN13_OUT SET_BIT(DDRB, DDB7)

#endif // RTOS_ARDUINO_PINS_INCLUDED
